name: avm
description: AntiVirus Monitor
branding:
  color: red
  icon: monitor
inputs:
  files:
    description: list of files to scan (newline separated)
runs:
  using: node12
  main: action/index.dist.js
