name: avm

on:
  watch:
    types: [started]
  #schedule:
  #  - cron: '0 14,20 * * *'

jobs:
  scan:
    if: github.actor == github.event.repository.owner.login

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - run: .\avm.ps1 scan https://github.com/billziss-gh/winfsp/releases/download/v1.6/winfsp-1.6.20027.msi
