name: test action

on: [push]

jobs:
  test:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: billziss-gh/avm@master
      with:
        files: |
            https://github.com/billziss-gh/winfsp/releases/download/v1.6/winfsp-1.6.20027.msi
            https://github.com/billziss-gh/winfsp/releases/download/v1.7B1/winfsp-1.7.20038.msi
